Feature/decentralized bonder prep
hop-protocol/contracts pull request #79
Opened 2021-08-31 00:19 UTC by cwhinfrey

- Broadcast a bonder address when sending from L2
- Separate whitelist out into Bonder Registry

2021-08-31 04:36 UTC, shanefontaine requested changes

2021-08-31 04:36 UTC, shanefontaine commented on contracts/bridges/Accounting.sol
> +    IBonderRegistry registry;
Should be labeled `public` or `private` for consistency

2021-08-31 04:36 UTC, shanefontaine commented on contracts/bridges/Accounting.sol
> +        _credit[bonder] = _credit[bonder].add(amount);
Should this call `addCredit()`?

2021-08-31 04:36 UTC, shanefontaine commented on contracts/bridges/Accounting.sol
> +        _credit[msg.sender] = _credit[msg.sender].sub(amount);
Should this call a new function, `subCredit()`?

2021-08-31 04:36 UTC, shanefontaine commented on contracts/bridges/Accounting.sol
>      function _addDebit(address bonder, uint256 amount) internal {
Can `_addDebit()` be removed now?

2021-08-31 04:36 UTC, shanefontaine commented on contracts/bridges/BonderRegistry.sol
> +    mapping(address => bool) isBonder;
Should be labeled public or private for consistency

2021-08-31 04:36 UTC, shanefontaine commented on contracts/bridges/Accounting.sol
> +        return registry.isBonderAllowed(maybeBonder, _credit[maybeBonder]);
Depending on the future registry implementation, it might make sense to have an `getIsBonder()` and a separate `getIsBonderWithCredit()` to differentiate between bonders who have been added to the registry but are not yet staked, do not have current credit, etc. Pretty loose opinion on this one.

2021-09-01 00:53 UTC, cwhinfrey commented on contracts/bridges/Accounting.sol
> +        _credit[bonder] = _credit[bonder].add(amount);
Leaving as is like we discussed

2021-09-01 00:53 UTC, cwhinfrey commented on contracts/bridges/Accounting.sol
> +        _credit[msg.sender] = _credit[msg.sender].sub(amount);
Leaving as is like we discussed

2021-09-01 00:54 UTC, cwhinfrey commented on contracts/bridges/Accounting.sol
>      function _addDebit(address bonder, uint256 amount) internal {
We still need this for when the bonder bonds a transfer or transfer root

2021-09-01 00:55 UTC, cwhinfrey commented on contracts/bridges/Accounting.sol
> +        return registry.isBonderAllowed(maybeBonder, _credit[maybeBonder]);
I made the `isBonder` mapping public which should do the trick

2021-09-01 01:29 UTC, shanefontaine commented on contracts/bridges/Accounting.sol
> +        return registry.isBonderAllowed(maybeBonder, _credit[maybeBonder]);
Yea that is 👍

2021-09-01 01:29 UTC, shanefontaine commented
Good to go @cwhinfrey

2021-09-01 02:14 UTC, shanefontaine approved these changes
👍

2021-09-01 02:14 UTC, merged